spring:
  profiles:
#    active: dev
    active: prod



application:
  # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
  cors:
    allowed-origins: "*"
    allowed-methods: GET, PUT, POST, DELETE, OPTIONS
    allowed-headers: "*"
    exposed-headers: access-control-allow-headers,access-control-allow-methods,access-control-allow-origin,access-control-max-age,X-Frame-Options
    allow-credentials: false
    max-age: 1800

# Huawei content moderation SDK
contentModeration:
  ak: "IGV90FGWXWBO75N6W1EM"
  sk: "voEnEVMbWzbxW1ljf8WXvxmNHSki3ldNbSAn66NB"
  # HongKong: ap-southeast-1
  # Singapore: ap-southeast-3
  regionId: "ap-southeast-1"