server:
  port: 8284

spring:

  jackson.date-format: yyyy-MM-dd HH:mm:ss
  jackson.time-zone: GMT+8

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://b1f0eec216ea4c:7b371b59@eu-cdbr-west-01.cleardb.com/heroku_7662f34ad93a4a5?reconnect=true
    username: b1f0eec216ea4c
    password: 7b371b59
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_query_cache: true
      hibernate.cache.use_second_level_cache: false
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
      hibernate.cache.provider_configuration_file_resource_path: classpath:config/ehcache.xml

logging:
  config: classpath:config/logback-prod.xml

application:

  project:
    name: GameMythic
    code: gm
    baseUrl: http://127.0.0.1
