spring:
  profiles:
    active: dev
  jackson.date-format: yyyy-MM-dd HH:mm:ss
  jackson.time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      # Maximum requested file size
      max-request-size: 100MB
      # Set the maximum length of a single file
      max-file-size: 20MB
      # Disk write when the file reaches
      file-size-threshold: 20MB
application:
  # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
  cors:
    allowed-origins: "*"
    allowed-methods: GET, PUT, POST, DELETE, OPTIONS
    allowed-headers: "*"
    exposed-headers: access-control-allow-headers,access-control-allow-methods,access-control-allow-origin,access-control-max-age,X-Frame-Options
    allow-credentials: false
    max-age:
server:
  port: 8184
logging:
  config: classpath:config/logback-dev.xml
